packages:
  - packages/*
  - examples/*
  - e2e/fixtures/*
  - '!**/dist'

linkWorkspacePackages: true

patchedDependencies:
  ps-tree: patches/ps-tree.patch

preferWorkspacePackages: true

saveWorkspaceProtocol: true
