packages:
  - packages/*
  - examples/*
  - e2e/fixtures/*
  - '!**/dist'

linkWorkspacePackages: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@vitejs/plugin-rsc'
  - react
  - react-dom
  - react-server-dom-webpack
  - scheduler
  - waku-jotai

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

preferWorkspacePackages: true

saveWorkspaceProtocol: true
